SELECT TOP (1000) [ID]
      ,[Barcode]
      ,[Tên tài xế]
      ,[Biển số xe]
      ,[Nhiên liệu]
      ,[Loại nhiên liệu]
      ,[Trạm cấp phát]
      ,[Ngày nhập nhiên liệu]
  FROM [lucdeptrai].[dbo].[test]
