SELECT TOP (1000) [id]
      ,[username]
      ,[Barcode]
      ,[Tên tài xế]
      ,[Biển số xe]
      ,[Nhiên liệu]
      ,[Loại nhiên liệu]
      ,[Trạm cấp phát]
      ,[executed_at]
      ,[Ngày nhập nhiên liệu]
  FROM [lucdeptrai].[dbo].[tesst]
